services:
  db:
    image: mariadb:10.11
    container_name: nrl-prosjekt-gr14-2025h-db-1
    
    # Bruker .env for å hente passord, slik at passord ikke er offentlig
    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mysqldata:/var/lib/mysql

  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: Development
      # ASP.NET connection string bruker .env for sikkerhet
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=${MYSQL_DATABASE};user=root;password=${MYSQL_ROOT_PASSWORD}"
    ports:
      - "8080:8080"
    volumes:
      - ./WebApplication1/wwwroot/images:/app/wwwroot/images

  ef-tools:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - .:/src
      - ~/.nuget/packages:/root/.nuget/packages
    depends_on:
      - db
    
    env_file:
      - .env

    environment:
      - ConnectionStrings__DefaultConnection=server=db;database=${MYSQL_DATABASE};user=root;password=${MYSQL_ROOT_PASSWORD};
    entrypoint: >
      bash -c "dotnet tool install --global dotnet-ef --version 9.0.9 &&
      export PATH=$$PATH:/root/.dotnet/tools &&
      exec dotnet ef $${@}" --

  ef-add:
    extends: ef-tools
    entrypoint: >
      bash -c "dotnet tool install --global dotnet-ef --version 9.0.9 &&
      export PATH=$$PATH:/root/.dotnet/tools &&
      MIGRATION_NAME=$${MIGRATION_NAME:-Init} &&
      exec dotnet ef migrations add $$MIGRATION_NAME --project WebApplication1/WebApplication1.csproj --startup-project WebApplication1"

  ef-update:
    extends: ef-tools
    command: database update --project WebApplication1/WebApplication1.csproj --startup-project WebApplication1

volumes:
  mysqldata:
    name: nrl-db-data