// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250916154934_AddPrimaryKeyAndReporterGpsToObstacleData")]
    partial class AddPrimaryKeyAndReporterGpsToObstacleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ObstacleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObstacleDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ObstacleHeight")
                        .HasColumnType("double");

                    b.Property<double>("ObstacleLatitude")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleLineCoords")
                        .HasColumnType("longtext");

                    b.Property<double>("ObstacleLongitude")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("ObstacleRadius")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ReporterAccuracy")
                        .HasColumnType("int");

                    b.Property<double?>("ReporterLatitude")
                        .HasColumnType("double");

                    b.Property<double?>("ReporterLongitude")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Obstacles");
                });
#pragma warning restore 612, 618
        }
    }
}
