// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DataInfrastructure;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251115032501_UserStuff")]
    partial class UserStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Entities.ObstacleData", b =>
                {
                    b.Property<int>("ObstacleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ObstacleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstacleID"));

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObstacleDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleGeoJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("ObstacleHasLight")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("ObstacleHeight")
                        .HasColumnType("double");

                    b.Property<double?>("ObstacleLatitude")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleLineCoordinates")
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleLineLength")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("ObstacleLongitude")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("ObstacleRadius")
                        .HasColumnType("double");

                    b.Property<DateTime>("ObstacleRegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObstacleType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("ObstacleID");

                    b.HasIndex("ReportID")
                        .IsUnique();

                    b.ToTable("ObstacleData");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrganizationID"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Pilot", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserData_UserID");

                    b.Property<string>("AircraftType")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("ULicenseNumber")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("UserID");

                    b.ToTable("Pilot", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Registrar", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserData_UserID");

                    b.Property<string>("Department")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("UserID");

                    b.ToTable("Registrar", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int")
                        .HasColumnName("Organization_OrganizationID");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Role")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("UserID");

                    b.HasIndex("OrganizationID")
                        .HasDatabaseName("UserData_Organization_idx");

                    b.ToTable("UserData", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.ReportItem", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Organization")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("PilotID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SubmittedByEmail")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SubmittedByName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ReportID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("PilotID");

                    b.ToTable("ReportItem");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.ObstacleData", b =>
                {
                    b.HasOne("WebApplication1.Models.ReportItem", "ReportItem")
                        .WithOne("ReportObstacle")
                        .HasForeignKey("WebApplication1.Models.Entities.ObstacleData", "ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportItem");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Pilot", b =>
                {
                    b.HasOne("WebApplication1.Models.Entities.UserEntity", "User")
                        .WithOne("Pilot")
                        .HasForeignKey("WebApplication1.Models.Entities.Pilot", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Registrar", b =>
                {
                    b.HasOne("WebApplication1.Models.Entities.UserEntity", "User")
                        .WithOne("Registrar")
                        .HasForeignKey("WebApplication1.Models.Entities.Registrar", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.UserEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("WebApplication1.Models.ReportItem", b =>
                {
                    b.HasOne("WebApplication1.Models.Entities.Organization", "OrganizationRef")
                        .WithMany("Reports")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApplication1.Models.Entities.Pilot", "Pilot")
                        .WithMany("Reports")
                        .HasForeignKey("PilotID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizationRef");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Organization", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Pilot", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.UserEntity", b =>
                {
                    b.Navigation("Pilot");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("WebApplication1.Models.ReportItem", b =>
                {
                    b.Navigation("ReportObstacle");
                });
#pragma warning restore 612, 618
        }
    }
}
