// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DataInfrastructure;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105112935_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ObstacleData", b =>
                {
                    b.Property<int>("ObstacleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ObstacleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstacleID"));

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObstacleDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleGeoJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("ObstacleHasLight")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("ObstacleHeight")
                        .HasColumnType("double");

                    b.Property<double?>("ObstacleLatitude")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleLineCoordinates")
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleLineLength")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("ObstacleLongitude")
                        .HasColumnType("double");

                    b.Property<string>("ObstacleName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("ObstacleRadius")
                        .HasColumnType("double");

                    b.Property<DateTime>("ObstacleRegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObstacleType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.HasKey("ObstacleID");

                    b.HasIndex("ReportID")
                        .IsUnique();

                    b.ToTable("ObstacleData");
                });

            modelBuilder.Entity("WebApplication1.Models.ReportItem", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Organization")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("PilotID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SubmittedByEmail")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SubmittedByName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ReportID");

                    b.ToTable("ReportItem");
                });

            modelBuilder.Entity("WebApplication1.Models.ObstacleData", b =>
                {
                    b.HasOne("WebApplication1.Models.ReportItem", "ReportItem")
                        .WithOne("ReportObstacle")
                        .HasForeignKey("WebApplication1.Models.ObstacleData", "ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportItem");
                });

            modelBuilder.Entity("WebApplication1.Models.ReportItem", b =>
                {
                    b.Navigation("ReportObstacle");
                });
#pragma warning restore 612, 618
        }
    }
}
