// Databasetable for passwordreset-tokens that links the hash to the user and expiration time.
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models.Entities
{
    [Table("PasswordResetTokens")]
    public class PasswordResetToken
    {
        // Primary key generated by the database.
        [Key]
        public int Id { get; set; }

        // Connection to the user the token applies to.
        [Required]
        [Column("UserID")]
        public int UserId { get; set; }

        // Hash value is stored in the database so that the raw token is not in plain text.
        [Required]
        [StringLength(128)]
        public string TokenHash { get; set; } = string.Empty;

        // When the token was created and when it expires.
        public DateTime CreatedAtUtc { get; set; }

        public DateTime ExpiresAtUtc { get; set; }

        // Sets when the token has been used, otherwise null.
        public DateTime? RedeemedAtUtc { get; set; }

        // Navigationreference for Entity Framework.
        [ForeignKey(nameof(UserId))]
        public UserEntity? User { get; set; }
    }
}
